name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 当blog-source的main分支收到推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}  # 明确指定 token

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: |
        npm install -g hexo-cli
        npm install
        npm install hexo-generator-tag hexo-generator-category --save  # 添加分类和标签插件

    - name: Configure Git
      run: |
        git config --global user.name "guohaolu"
        git config --global user.email "1670212878@qq.com"

    - name: Build
      run: |
        hexo clean
        hexo generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}  # 需要创建个人访问令牌
        external_repository: guohaolu/guohaolu.github.io  # 指定外部仓库
        publish_dir: ./public
        publish_branch: main  # 部署到main分支
        commit_message: ${{ github.event.head_commit.message }}
        force: true